version: 0.2

phases:
  build:
    commands:
      - mvn compile
  post_build:
    commands:
      - mvn package
      - echo "******** Uploading to S3 ********"
      - aws s3 cp target/FantasyEPLMonitor.jar s3://fantasyeplmatchtrackerfeature/bin/FantasyEPLMonitor.jar
artifacts:
  files:
    - target/FantasyEPLMonitor.jar
  discard-paths: yes
#  base-directory: location