version: 0.2

phases:
  build:
    commands:
      - mvn compile
  post_build:
    commands:
      - mvn package
      - echo "******** Uploading to S3 ********"
      - aws s3 cp target/FantasyEPLMonitor-0.5-SNAPSHOT.jar s3://fantasyeplmatchtracker/bin/
artifacts:
  files:
    - target/FantasyEPLMonitor-0.5-SNAPSHOT.jar
  discard-paths: yes
#  base-directory: location